# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
release:
  github:
    owner: pivotal-cf
    name: om
  draft: true
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  ldflags:
  - -s -w -X "main.version={{.Version}}"
archives:
- id: github
  format: binary
  name_template: "om-{{ .Os }}"
- id: homebrew
  format: "tar.gz"
  name_template: "om-{{ .Os }}"
  format_overrides:
  - goos: windows
    format: zip
brews:
- github:
    owner: pivotal-cf
    name: om
  ids:
  - homebrew
  test: |
    system "#{bin}/om --version"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
