# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Om < Formula
  desc ""
  homepage ""
  version "7.7.0"

  on_macos do
    url "https://github.com/pivotal-cf/om/releases/download/7.7.0/om-darwin-7.7.0.tar.gz"
    sha256 "628281d813bc113c959d7fb83a6cdd8bd05e2d32b78b9b113400274a225ddb25"

    def install
      bin.install "om"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Om
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/om/releases/download/7.7.0/om-linux-7.7.0.tar.gz"
      sha256 "ffcbe07f81500ab353bf2ee452580bd3610bd4eca1a74e6a5e92e109914f6704"

      def install
        bin.install "om"
      end
    end
  end

  test do
    system "#{bin}/om --version"
  end
end
