# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Om < Formula
  desc ""
  homepage ""
  version "7.21.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/om/releases/download/7.21.0/om-darwin-amd64-7.21.0.tar.gz"
      sha256 "0dbe6effe5e46a9f91282492c75edb3b4b035a04231fb203b2c8bf615a0611ea"

      define_method(:install) do
        bin.install "om"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pivotal-cf/om/releases/download/7.21.0/om-darwin-arm64-7.21.0.tar.gz"
      sha256 "3adb8757d593a52544fcc0a57596b0aabd6ff5b83d5cc0ad145df8b5fc2f0f3f"

      define_method(:install) do
        bin.install "om"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivotal-cf/om/releases/download/7.21.0/om-linux-amd64-7.21.0.tar.gz"
      sha256 "f7606956b83af0b9d8f0cdf2af364094628bfc9ad6d39b55e3048b6b40eb219b"
      define_method(:install) do
        bin.install "om"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivotal-cf/om/releases/download/7.21.0/om-linux-arm64-7.21.0.tar.gz"
      sha256 "cc6767bb08de63c014deff8d8ea22116e7180ff8734efbbc415db6260e9ca8a4"
      define_method(:install) do
        bin.install "om"
      end
    end
  end

  test do
    system "#{bin}/om --version"
  end
end
