# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Om < Formula
  desc ""
  homepage ""
  version "7.3.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/om/releases/download/7.3.0/om-darwin-7.3.0.tar.gz"
      sha256 "37cd52a0ec03a96a282e70f96950d980f26d77026d0f3f8fb01a84bd27cca9dc"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/om/releases/download/7.3.0/om-linux-7.3.0.tar.gz"
      sha256 "ce7a4f620a1ad978147a1f2cba4a0b34549e97dd40faf25cbccd8dcb1bee2d2b"
    end
  end

  def install
    bin.install "om"
  end

  test do
    system "#{bin}/om --version"
  end
end
