package commands_test

import (
	"fmt"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"github.com/pivotal-cf/jhanda"
	"github.com/pivotal-cf/om/commands"
	"github.com/pivotal-cf/om/commands/fakes"
)

var _ = Describe("RegenerateCertificates", func() {
	var (
		fakeService *fakes.RegenerateCertificatesService
		fakeLogger  *fakes.Logger
		command     commands.RegenerateCertificates
	)

	BeforeEach(func() {
		fakeService = &fakes.RegenerateCertificatesService{}
		fakeLogger = &fakes.Logger{}
		command = commands.NewRegenerateCertificates(fakeService, fakeLogger)
	})

	Describe("Execute", func() {
		It("makes a request to the Opsman to regenerate the certificates generated by an inactive certificate authority", func() {
			err := command.Execute([]string{})
			Expect(err).ToNot(HaveOccurred())
			Expect(fakeService.RegenerateCertificatesCallCount()).To(Equal(1))

			Expect(fakeLogger.PrintfCallCount()).To(Equal(1))
			format, content := fakeLogger.PrintfArgsForCall(0)
			Expect(fmt.Sprintf(format, content...)).To(Equal("Certificates regenerated.\n"))
		})
	})

	Describe("Usage", func() {
		It("returns usage info", func() {
			usage := command.Usage()
			Expect(usage).To(Equal(jhanda.Usage{
				Description:      "This authenticated command deletes all non-configurable certificates in Ops Manager so they will automatically be regenerated on the next apply-changes",
				ShortDescription: "deletes all non-configurable certificates in Ops Manager so they will automatically be regenerated on the next apply-changes",
			}))
		})
	})
})
