// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/pivotal-cf/om/api"
)

type ConfigureDirectorService struct {
	ConfigureJobResourceConfigStub        func(string, map[string]interface{}) error
	configureJobResourceConfigMutex       sync.RWMutex
	configureJobResourceConfigArgsForCall []struct {
		arg1 string
		arg2 map[string]interface{}
	}
	configureJobResourceConfigReturns struct {
		result1 error
	}
	configureJobResourceConfigReturnsOnCall map[int]struct {
		result1 error
	}
	CreateCustomVMTypesStub        func(api.CreateVMTypes) error
	createCustomVMTypesMutex       sync.RWMutex
	createCustomVMTypesArgsForCall []struct {
		arg1 api.CreateVMTypes
	}
	createCustomVMTypesReturns struct {
		result1 error
	}
	createCustomVMTypesReturnsOnCall map[int]struct {
		result1 error
	}
	CreateStagedVMExtensionStub        func(api.CreateVMExtension) error
	createStagedVMExtensionMutex       sync.RWMutex
	createStagedVMExtensionArgsForCall []struct {
		arg1 api.CreateVMExtension
	}
	createStagedVMExtensionReturns struct {
		result1 error
	}
	createStagedVMExtensionReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteCustomVMTypesStub        func() error
	deleteCustomVMTypesMutex       sync.RWMutex
	deleteCustomVMTypesArgsForCall []struct {
	}
	deleteCustomVMTypesReturns struct {
		result1 error
	}
	deleteCustomVMTypesReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteVMExtensionStub        func(string) error
	deleteVMExtensionMutex       sync.RWMutex
	deleteVMExtensionArgsForCall []struct {
		arg1 string
	}
	deleteVMExtensionReturns struct {
		result1 error
	}
	deleteVMExtensionReturnsOnCall map[int]struct {
		result1 error
	}
	GetStagedProductByNameStub        func(string) (api.StagedProductsFindOutput, error)
	getStagedProductByNameMutex       sync.RWMutex
	getStagedProductByNameArgsForCall []struct {
		arg1 string
	}
	getStagedProductByNameReturns struct {
		result1 api.StagedProductsFindOutput
		result2 error
	}
	getStagedProductByNameReturnsOnCall map[int]struct {
		result1 api.StagedProductsFindOutput
		result2 error
	}
	GetStagedProductManifestStub        func(string) (string, error)
	getStagedProductManifestMutex       sync.RWMutex
	getStagedProductManifestArgsForCall []struct {
		arg1 string
	}
	getStagedProductManifestReturns struct {
		result1 string
		result2 error
	}
	getStagedProductManifestReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	InfoStub        func() (api.Info, error)
	infoMutex       sync.RWMutex
	infoArgsForCall []struct {
	}
	infoReturns struct {
		result1 api.Info
		result2 error
	}
	infoReturnsOnCall map[int]struct {
		result1 api.Info
		result2 error
	}
	ListInstallationsStub        func() ([]api.InstallationsServiceOutput, error)
	listInstallationsMutex       sync.RWMutex
	listInstallationsArgsForCall []struct {
	}
	listInstallationsReturns struct {
		result1 []api.InstallationsServiceOutput
		result2 error
	}
	listInstallationsReturnsOnCall map[int]struct {
		result1 []api.InstallationsServiceOutput
		result2 error
	}
	ListStagedVMExtensionsStub        func() ([]api.VMExtension, error)
	listStagedVMExtensionsMutex       sync.RWMutex
	listStagedVMExtensionsArgsForCall []struct {
	}
	listStagedVMExtensionsReturns struct {
		result1 []api.VMExtension
		result2 error
	}
	listStagedVMExtensionsReturnsOnCall map[int]struct {
		result1 []api.VMExtension
		result2 error
	}
	ListVMTypesStub        func() ([]api.VMType, error)
	listVMTypesMutex       sync.RWMutex
	listVMTypesArgsForCall []struct {
	}
	listVMTypesReturns struct {
		result1 []api.VMType
		result2 error
	}
	listVMTypesReturnsOnCall map[int]struct {
		result1 []api.VMType
		result2 error
	}
	UpdateStagedDirectorAvailabilityZonesStub        func(api.AvailabilityZoneInput, bool) error
	updateStagedDirectorAvailabilityZonesMutex       sync.RWMutex
	updateStagedDirectorAvailabilityZonesArgsForCall []struct {
		arg1 api.AvailabilityZoneInput
		arg2 bool
	}
	updateStagedDirectorAvailabilityZonesReturns struct {
		result1 error
	}
	updateStagedDirectorAvailabilityZonesReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateStagedDirectorIAASConfigurationsStub        func(api.IAASConfigurationsInput) error
	updateStagedDirectorIAASConfigurationsMutex       sync.RWMutex
	updateStagedDirectorIAASConfigurationsArgsForCall []struct {
		arg1 api.IAASConfigurationsInput
	}
	updateStagedDirectorIAASConfigurationsReturns struct {
		result1 error
	}
	updateStagedDirectorIAASConfigurationsReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateStagedDirectorNetworkAndAZStub        func(api.NetworkAndAZConfiguration) error
	updateStagedDirectorNetworkAndAZMutex       sync.RWMutex
	updateStagedDirectorNetworkAndAZArgsForCall []struct {
		arg1 api.NetworkAndAZConfiguration
	}
	updateStagedDirectorNetworkAndAZReturns struct {
		result1 error
	}
	updateStagedDirectorNetworkAndAZReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateStagedDirectorNetworksStub        func(api.NetworkInput) error
	updateStagedDirectorNetworksMutex       sync.RWMutex
	updateStagedDirectorNetworksArgsForCall []struct {
		arg1 api.NetworkInput
	}
	updateStagedDirectorNetworksReturns struct {
		result1 error
	}
	updateStagedDirectorNetworksReturnsOnCall map[int]struct {
		result1 error
	}
	UpdateStagedDirectorPropertiesStub        func(api.DirectorProperties) error
	updateStagedDirectorPropertiesMutex       sync.RWMutex
	updateStagedDirectorPropertiesArgsForCall []struct {
		arg1 api.DirectorProperties
	}
	updateStagedDirectorPropertiesReturns struct {
		result1 error
	}
	updateStagedDirectorPropertiesReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ConfigureDirectorService) ConfigureJobResourceConfig(arg1 string, arg2 map[string]interface{}) error {
	fake.configureJobResourceConfigMutex.Lock()
	ret, specificReturn := fake.configureJobResourceConfigReturnsOnCall[len(fake.configureJobResourceConfigArgsForCall)]
	fake.configureJobResourceConfigArgsForCall = append(fake.configureJobResourceConfigArgsForCall, struct {
		arg1 string
		arg2 map[string]interface{}
	}{arg1, arg2})
	fake.recordInvocation("ConfigureJobResourceConfig", []interface{}{arg1, arg2})
	fake.configureJobResourceConfigMutex.Unlock()
	if fake.ConfigureJobResourceConfigStub != nil {
		return fake.ConfigureJobResourceConfigStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.configureJobResourceConfigReturns
	return fakeReturns.result1
}

func (fake *ConfigureDirectorService) ConfigureJobResourceConfigCallCount() int {
	fake.configureJobResourceConfigMutex.RLock()
	defer fake.configureJobResourceConfigMutex.RUnlock()
	return len(fake.configureJobResourceConfigArgsForCall)
}

func (fake *ConfigureDirectorService) ConfigureJobResourceConfigCalls(stub func(string, map[string]interface{}) error) {
	fake.configureJobResourceConfigMutex.Lock()
	defer fake.configureJobResourceConfigMutex.Unlock()
	fake.ConfigureJobResourceConfigStub = stub
}

func (fake *ConfigureDirectorService) ConfigureJobResourceConfigArgsForCall(i int) (string, map[string]interface{}) {
	fake.configureJobResourceConfigMutex.RLock()
	defer fake.configureJobResourceConfigMutex.RUnlock()
	argsForCall := fake.configureJobResourceConfigArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ConfigureDirectorService) ConfigureJobResourceConfigReturns(result1 error) {
	fake.configureJobResourceConfigMutex.Lock()
	defer fake.configureJobResourceConfigMutex.Unlock()
	fake.ConfigureJobResourceConfigStub = nil
	fake.configureJobResourceConfigReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) ConfigureJobResourceConfigReturnsOnCall(i int, result1 error) {
	fake.configureJobResourceConfigMutex.Lock()
	defer fake.configureJobResourceConfigMutex.Unlock()
	fake.ConfigureJobResourceConfigStub = nil
	if fake.configureJobResourceConfigReturnsOnCall == nil {
		fake.configureJobResourceConfigReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.configureJobResourceConfigReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) CreateCustomVMTypes(arg1 api.CreateVMTypes) error {
	fake.createCustomVMTypesMutex.Lock()
	ret, specificReturn := fake.createCustomVMTypesReturnsOnCall[len(fake.createCustomVMTypesArgsForCall)]
	fake.createCustomVMTypesArgsForCall = append(fake.createCustomVMTypesArgsForCall, struct {
		arg1 api.CreateVMTypes
	}{arg1})
	fake.recordInvocation("CreateCustomVMTypes", []interface{}{arg1})
	fake.createCustomVMTypesMutex.Unlock()
	if fake.CreateCustomVMTypesStub != nil {
		return fake.CreateCustomVMTypesStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.createCustomVMTypesReturns
	return fakeReturns.result1
}

func (fake *ConfigureDirectorService) CreateCustomVMTypesCallCount() int {
	fake.createCustomVMTypesMutex.RLock()
	defer fake.createCustomVMTypesMutex.RUnlock()
	return len(fake.createCustomVMTypesArgsForCall)
}

func (fake *ConfigureDirectorService) CreateCustomVMTypesCalls(stub func(api.CreateVMTypes) error) {
	fake.createCustomVMTypesMutex.Lock()
	defer fake.createCustomVMTypesMutex.Unlock()
	fake.CreateCustomVMTypesStub = stub
}

func (fake *ConfigureDirectorService) CreateCustomVMTypesArgsForCall(i int) api.CreateVMTypes {
	fake.createCustomVMTypesMutex.RLock()
	defer fake.createCustomVMTypesMutex.RUnlock()
	argsForCall := fake.createCustomVMTypesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ConfigureDirectorService) CreateCustomVMTypesReturns(result1 error) {
	fake.createCustomVMTypesMutex.Lock()
	defer fake.createCustomVMTypesMutex.Unlock()
	fake.CreateCustomVMTypesStub = nil
	fake.createCustomVMTypesReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) CreateCustomVMTypesReturnsOnCall(i int, result1 error) {
	fake.createCustomVMTypesMutex.Lock()
	defer fake.createCustomVMTypesMutex.Unlock()
	fake.CreateCustomVMTypesStub = nil
	if fake.createCustomVMTypesReturnsOnCall == nil {
		fake.createCustomVMTypesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createCustomVMTypesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) CreateStagedVMExtension(arg1 api.CreateVMExtension) error {
	fake.createStagedVMExtensionMutex.Lock()
	ret, specificReturn := fake.createStagedVMExtensionReturnsOnCall[len(fake.createStagedVMExtensionArgsForCall)]
	fake.createStagedVMExtensionArgsForCall = append(fake.createStagedVMExtensionArgsForCall, struct {
		arg1 api.CreateVMExtension
	}{arg1})
	fake.recordInvocation("CreateStagedVMExtension", []interface{}{arg1})
	fake.createStagedVMExtensionMutex.Unlock()
	if fake.CreateStagedVMExtensionStub != nil {
		return fake.CreateStagedVMExtensionStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.createStagedVMExtensionReturns
	return fakeReturns.result1
}

func (fake *ConfigureDirectorService) CreateStagedVMExtensionCallCount() int {
	fake.createStagedVMExtensionMutex.RLock()
	defer fake.createStagedVMExtensionMutex.RUnlock()
	return len(fake.createStagedVMExtensionArgsForCall)
}

func (fake *ConfigureDirectorService) CreateStagedVMExtensionCalls(stub func(api.CreateVMExtension) error) {
	fake.createStagedVMExtensionMutex.Lock()
	defer fake.createStagedVMExtensionMutex.Unlock()
	fake.CreateStagedVMExtensionStub = stub
}

func (fake *ConfigureDirectorService) CreateStagedVMExtensionArgsForCall(i int) api.CreateVMExtension {
	fake.createStagedVMExtensionMutex.RLock()
	defer fake.createStagedVMExtensionMutex.RUnlock()
	argsForCall := fake.createStagedVMExtensionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ConfigureDirectorService) CreateStagedVMExtensionReturns(result1 error) {
	fake.createStagedVMExtensionMutex.Lock()
	defer fake.createStagedVMExtensionMutex.Unlock()
	fake.CreateStagedVMExtensionStub = nil
	fake.createStagedVMExtensionReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) CreateStagedVMExtensionReturnsOnCall(i int, result1 error) {
	fake.createStagedVMExtensionMutex.Lock()
	defer fake.createStagedVMExtensionMutex.Unlock()
	fake.CreateStagedVMExtensionStub = nil
	if fake.createStagedVMExtensionReturnsOnCall == nil {
		fake.createStagedVMExtensionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createStagedVMExtensionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) DeleteCustomVMTypes() error {
	fake.deleteCustomVMTypesMutex.Lock()
	ret, specificReturn := fake.deleteCustomVMTypesReturnsOnCall[len(fake.deleteCustomVMTypesArgsForCall)]
	fake.deleteCustomVMTypesArgsForCall = append(fake.deleteCustomVMTypesArgsForCall, struct {
	}{})
	fake.recordInvocation("DeleteCustomVMTypes", []interface{}{})
	fake.deleteCustomVMTypesMutex.Unlock()
	if fake.DeleteCustomVMTypesStub != nil {
		return fake.DeleteCustomVMTypesStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteCustomVMTypesReturns
	return fakeReturns.result1
}

func (fake *ConfigureDirectorService) DeleteCustomVMTypesCallCount() int {
	fake.deleteCustomVMTypesMutex.RLock()
	defer fake.deleteCustomVMTypesMutex.RUnlock()
	return len(fake.deleteCustomVMTypesArgsForCall)
}

func (fake *ConfigureDirectorService) DeleteCustomVMTypesCalls(stub func() error) {
	fake.deleteCustomVMTypesMutex.Lock()
	defer fake.deleteCustomVMTypesMutex.Unlock()
	fake.DeleteCustomVMTypesStub = stub
}

func (fake *ConfigureDirectorService) DeleteCustomVMTypesReturns(result1 error) {
	fake.deleteCustomVMTypesMutex.Lock()
	defer fake.deleteCustomVMTypesMutex.Unlock()
	fake.DeleteCustomVMTypesStub = nil
	fake.deleteCustomVMTypesReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) DeleteCustomVMTypesReturnsOnCall(i int, result1 error) {
	fake.deleteCustomVMTypesMutex.Lock()
	defer fake.deleteCustomVMTypesMutex.Unlock()
	fake.DeleteCustomVMTypesStub = nil
	if fake.deleteCustomVMTypesReturnsOnCall == nil {
		fake.deleteCustomVMTypesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteCustomVMTypesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) DeleteVMExtension(arg1 string) error {
	fake.deleteVMExtensionMutex.Lock()
	ret, specificReturn := fake.deleteVMExtensionReturnsOnCall[len(fake.deleteVMExtensionArgsForCall)]
	fake.deleteVMExtensionArgsForCall = append(fake.deleteVMExtensionArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("DeleteVMExtension", []interface{}{arg1})
	fake.deleteVMExtensionMutex.Unlock()
	if fake.DeleteVMExtensionStub != nil {
		return fake.DeleteVMExtensionStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteVMExtensionReturns
	return fakeReturns.result1
}

func (fake *ConfigureDirectorService) DeleteVMExtensionCallCount() int {
	fake.deleteVMExtensionMutex.RLock()
	defer fake.deleteVMExtensionMutex.RUnlock()
	return len(fake.deleteVMExtensionArgsForCall)
}

func (fake *ConfigureDirectorService) DeleteVMExtensionCalls(stub func(string) error) {
	fake.deleteVMExtensionMutex.Lock()
	defer fake.deleteVMExtensionMutex.Unlock()
	fake.DeleteVMExtensionStub = stub
}

func (fake *ConfigureDirectorService) DeleteVMExtensionArgsForCall(i int) string {
	fake.deleteVMExtensionMutex.RLock()
	defer fake.deleteVMExtensionMutex.RUnlock()
	argsForCall := fake.deleteVMExtensionArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ConfigureDirectorService) DeleteVMExtensionReturns(result1 error) {
	fake.deleteVMExtensionMutex.Lock()
	defer fake.deleteVMExtensionMutex.Unlock()
	fake.DeleteVMExtensionStub = nil
	fake.deleteVMExtensionReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) DeleteVMExtensionReturnsOnCall(i int, result1 error) {
	fake.deleteVMExtensionMutex.Lock()
	defer fake.deleteVMExtensionMutex.Unlock()
	fake.DeleteVMExtensionStub = nil
	if fake.deleteVMExtensionReturnsOnCall == nil {
		fake.deleteVMExtensionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteVMExtensionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) GetStagedProductByName(arg1 string) (api.StagedProductsFindOutput, error) {
	fake.getStagedProductByNameMutex.Lock()
	ret, specificReturn := fake.getStagedProductByNameReturnsOnCall[len(fake.getStagedProductByNameArgsForCall)]
	fake.getStagedProductByNameArgsForCall = append(fake.getStagedProductByNameArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetStagedProductByName", []interface{}{arg1})
	fake.getStagedProductByNameMutex.Unlock()
	if fake.GetStagedProductByNameStub != nil {
		return fake.GetStagedProductByNameStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getStagedProductByNameReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ConfigureDirectorService) GetStagedProductByNameCallCount() int {
	fake.getStagedProductByNameMutex.RLock()
	defer fake.getStagedProductByNameMutex.RUnlock()
	return len(fake.getStagedProductByNameArgsForCall)
}

func (fake *ConfigureDirectorService) GetStagedProductByNameCalls(stub func(string) (api.StagedProductsFindOutput, error)) {
	fake.getStagedProductByNameMutex.Lock()
	defer fake.getStagedProductByNameMutex.Unlock()
	fake.GetStagedProductByNameStub = stub
}

func (fake *ConfigureDirectorService) GetStagedProductByNameArgsForCall(i int) string {
	fake.getStagedProductByNameMutex.RLock()
	defer fake.getStagedProductByNameMutex.RUnlock()
	argsForCall := fake.getStagedProductByNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ConfigureDirectorService) GetStagedProductByNameReturns(result1 api.StagedProductsFindOutput, result2 error) {
	fake.getStagedProductByNameMutex.Lock()
	defer fake.getStagedProductByNameMutex.Unlock()
	fake.GetStagedProductByNameStub = nil
	fake.getStagedProductByNameReturns = struct {
		result1 api.StagedProductsFindOutput
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) GetStagedProductByNameReturnsOnCall(i int, result1 api.StagedProductsFindOutput, result2 error) {
	fake.getStagedProductByNameMutex.Lock()
	defer fake.getStagedProductByNameMutex.Unlock()
	fake.GetStagedProductByNameStub = nil
	if fake.getStagedProductByNameReturnsOnCall == nil {
		fake.getStagedProductByNameReturnsOnCall = make(map[int]struct {
			result1 api.StagedProductsFindOutput
			result2 error
		})
	}
	fake.getStagedProductByNameReturnsOnCall[i] = struct {
		result1 api.StagedProductsFindOutput
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) GetStagedProductManifest(arg1 string) (string, error) {
	fake.getStagedProductManifestMutex.Lock()
	ret, specificReturn := fake.getStagedProductManifestReturnsOnCall[len(fake.getStagedProductManifestArgsForCall)]
	fake.getStagedProductManifestArgsForCall = append(fake.getStagedProductManifestArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetStagedProductManifest", []interface{}{arg1})
	fake.getStagedProductManifestMutex.Unlock()
	if fake.GetStagedProductManifestStub != nil {
		return fake.GetStagedProductManifestStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getStagedProductManifestReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ConfigureDirectorService) GetStagedProductManifestCallCount() int {
	fake.getStagedProductManifestMutex.RLock()
	defer fake.getStagedProductManifestMutex.RUnlock()
	return len(fake.getStagedProductManifestArgsForCall)
}

func (fake *ConfigureDirectorService) GetStagedProductManifestCalls(stub func(string) (string, error)) {
	fake.getStagedProductManifestMutex.Lock()
	defer fake.getStagedProductManifestMutex.Unlock()
	fake.GetStagedProductManifestStub = stub
}

func (fake *ConfigureDirectorService) GetStagedProductManifestArgsForCall(i int) string {
	fake.getStagedProductManifestMutex.RLock()
	defer fake.getStagedProductManifestMutex.RUnlock()
	argsForCall := fake.getStagedProductManifestArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ConfigureDirectorService) GetStagedProductManifestReturns(result1 string, result2 error) {
	fake.getStagedProductManifestMutex.Lock()
	defer fake.getStagedProductManifestMutex.Unlock()
	fake.GetStagedProductManifestStub = nil
	fake.getStagedProductManifestReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) GetStagedProductManifestReturnsOnCall(i int, result1 string, result2 error) {
	fake.getStagedProductManifestMutex.Lock()
	defer fake.getStagedProductManifestMutex.Unlock()
	fake.GetStagedProductManifestStub = nil
	if fake.getStagedProductManifestReturnsOnCall == nil {
		fake.getStagedProductManifestReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getStagedProductManifestReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) Info() (api.Info, error) {
	fake.infoMutex.Lock()
	ret, specificReturn := fake.infoReturnsOnCall[len(fake.infoArgsForCall)]
	fake.infoArgsForCall = append(fake.infoArgsForCall, struct {
	}{})
	fake.recordInvocation("Info", []interface{}{})
	fake.infoMutex.Unlock()
	if fake.InfoStub != nil {
		return fake.InfoStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.infoReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ConfigureDirectorService) InfoCallCount() int {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	return len(fake.infoArgsForCall)
}

func (fake *ConfigureDirectorService) InfoCalls(stub func() (api.Info, error)) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = stub
}

func (fake *ConfigureDirectorService) InfoReturns(result1 api.Info, result2 error) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = nil
	fake.infoReturns = struct {
		result1 api.Info
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) InfoReturnsOnCall(i int, result1 api.Info, result2 error) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = nil
	if fake.infoReturnsOnCall == nil {
		fake.infoReturnsOnCall = make(map[int]struct {
			result1 api.Info
			result2 error
		})
	}
	fake.infoReturnsOnCall[i] = struct {
		result1 api.Info
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) ListInstallations() ([]api.InstallationsServiceOutput, error) {
	fake.listInstallationsMutex.Lock()
	ret, specificReturn := fake.listInstallationsReturnsOnCall[len(fake.listInstallationsArgsForCall)]
	fake.listInstallationsArgsForCall = append(fake.listInstallationsArgsForCall, struct {
	}{})
	fake.recordInvocation("ListInstallations", []interface{}{})
	fake.listInstallationsMutex.Unlock()
	if fake.ListInstallationsStub != nil {
		return fake.ListInstallationsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listInstallationsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ConfigureDirectorService) ListInstallationsCallCount() int {
	fake.listInstallationsMutex.RLock()
	defer fake.listInstallationsMutex.RUnlock()
	return len(fake.listInstallationsArgsForCall)
}

func (fake *ConfigureDirectorService) ListInstallationsCalls(stub func() ([]api.InstallationsServiceOutput, error)) {
	fake.listInstallationsMutex.Lock()
	defer fake.listInstallationsMutex.Unlock()
	fake.ListInstallationsStub = stub
}

func (fake *ConfigureDirectorService) ListInstallationsReturns(result1 []api.InstallationsServiceOutput, result2 error) {
	fake.listInstallationsMutex.Lock()
	defer fake.listInstallationsMutex.Unlock()
	fake.ListInstallationsStub = nil
	fake.listInstallationsReturns = struct {
		result1 []api.InstallationsServiceOutput
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) ListInstallationsReturnsOnCall(i int, result1 []api.InstallationsServiceOutput, result2 error) {
	fake.listInstallationsMutex.Lock()
	defer fake.listInstallationsMutex.Unlock()
	fake.ListInstallationsStub = nil
	if fake.listInstallationsReturnsOnCall == nil {
		fake.listInstallationsReturnsOnCall = make(map[int]struct {
			result1 []api.InstallationsServiceOutput
			result2 error
		})
	}
	fake.listInstallationsReturnsOnCall[i] = struct {
		result1 []api.InstallationsServiceOutput
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) ListStagedVMExtensions() ([]api.VMExtension, error) {
	fake.listStagedVMExtensionsMutex.Lock()
	ret, specificReturn := fake.listStagedVMExtensionsReturnsOnCall[len(fake.listStagedVMExtensionsArgsForCall)]
	fake.listStagedVMExtensionsArgsForCall = append(fake.listStagedVMExtensionsArgsForCall, struct {
	}{})
	fake.recordInvocation("ListStagedVMExtensions", []interface{}{})
	fake.listStagedVMExtensionsMutex.Unlock()
	if fake.ListStagedVMExtensionsStub != nil {
		return fake.ListStagedVMExtensionsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listStagedVMExtensionsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ConfigureDirectorService) ListStagedVMExtensionsCallCount() int {
	fake.listStagedVMExtensionsMutex.RLock()
	defer fake.listStagedVMExtensionsMutex.RUnlock()
	return len(fake.listStagedVMExtensionsArgsForCall)
}

func (fake *ConfigureDirectorService) ListStagedVMExtensionsCalls(stub func() ([]api.VMExtension, error)) {
	fake.listStagedVMExtensionsMutex.Lock()
	defer fake.listStagedVMExtensionsMutex.Unlock()
	fake.ListStagedVMExtensionsStub = stub
}

func (fake *ConfigureDirectorService) ListStagedVMExtensionsReturns(result1 []api.VMExtension, result2 error) {
	fake.listStagedVMExtensionsMutex.Lock()
	defer fake.listStagedVMExtensionsMutex.Unlock()
	fake.ListStagedVMExtensionsStub = nil
	fake.listStagedVMExtensionsReturns = struct {
		result1 []api.VMExtension
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) ListStagedVMExtensionsReturnsOnCall(i int, result1 []api.VMExtension, result2 error) {
	fake.listStagedVMExtensionsMutex.Lock()
	defer fake.listStagedVMExtensionsMutex.Unlock()
	fake.ListStagedVMExtensionsStub = nil
	if fake.listStagedVMExtensionsReturnsOnCall == nil {
		fake.listStagedVMExtensionsReturnsOnCall = make(map[int]struct {
			result1 []api.VMExtension
			result2 error
		})
	}
	fake.listStagedVMExtensionsReturnsOnCall[i] = struct {
		result1 []api.VMExtension
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) ListVMTypes() ([]api.VMType, error) {
	fake.listVMTypesMutex.Lock()
	ret, specificReturn := fake.listVMTypesReturnsOnCall[len(fake.listVMTypesArgsForCall)]
	fake.listVMTypesArgsForCall = append(fake.listVMTypesArgsForCall, struct {
	}{})
	fake.recordInvocation("ListVMTypes", []interface{}{})
	fake.listVMTypesMutex.Unlock()
	if fake.ListVMTypesStub != nil {
		return fake.ListVMTypesStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listVMTypesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ConfigureDirectorService) ListVMTypesCallCount() int {
	fake.listVMTypesMutex.RLock()
	defer fake.listVMTypesMutex.RUnlock()
	return len(fake.listVMTypesArgsForCall)
}

func (fake *ConfigureDirectorService) ListVMTypesCalls(stub func() ([]api.VMType, error)) {
	fake.listVMTypesMutex.Lock()
	defer fake.listVMTypesMutex.Unlock()
	fake.ListVMTypesStub = stub
}

func (fake *ConfigureDirectorService) ListVMTypesReturns(result1 []api.VMType, result2 error) {
	fake.listVMTypesMutex.Lock()
	defer fake.listVMTypesMutex.Unlock()
	fake.ListVMTypesStub = nil
	fake.listVMTypesReturns = struct {
		result1 []api.VMType
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) ListVMTypesReturnsOnCall(i int, result1 []api.VMType, result2 error) {
	fake.listVMTypesMutex.Lock()
	defer fake.listVMTypesMutex.Unlock()
	fake.ListVMTypesStub = nil
	if fake.listVMTypesReturnsOnCall == nil {
		fake.listVMTypesReturnsOnCall = make(map[int]struct {
			result1 []api.VMType
			result2 error
		})
	}
	fake.listVMTypesReturnsOnCall[i] = struct {
		result1 []api.VMType
		result2 error
	}{result1, result2}
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorAvailabilityZones(arg1 api.AvailabilityZoneInput, arg2 bool) error {
	fake.updateStagedDirectorAvailabilityZonesMutex.Lock()
	ret, specificReturn := fake.updateStagedDirectorAvailabilityZonesReturnsOnCall[len(fake.updateStagedDirectorAvailabilityZonesArgsForCall)]
	fake.updateStagedDirectorAvailabilityZonesArgsForCall = append(fake.updateStagedDirectorAvailabilityZonesArgsForCall, struct {
		arg1 api.AvailabilityZoneInput
		arg2 bool
	}{arg1, arg2})
	fake.recordInvocation("UpdateStagedDirectorAvailabilityZones", []interface{}{arg1, arg2})
	fake.updateStagedDirectorAvailabilityZonesMutex.Unlock()
	if fake.UpdateStagedDirectorAvailabilityZonesStub != nil {
		return fake.UpdateStagedDirectorAvailabilityZonesStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.updateStagedDirectorAvailabilityZonesReturns
	return fakeReturns.result1
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorAvailabilityZonesCallCount() int {
	fake.updateStagedDirectorAvailabilityZonesMutex.RLock()
	defer fake.updateStagedDirectorAvailabilityZonesMutex.RUnlock()
	return len(fake.updateStagedDirectorAvailabilityZonesArgsForCall)
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorAvailabilityZonesCalls(stub func(api.AvailabilityZoneInput, bool) error) {
	fake.updateStagedDirectorAvailabilityZonesMutex.Lock()
	defer fake.updateStagedDirectorAvailabilityZonesMutex.Unlock()
	fake.UpdateStagedDirectorAvailabilityZonesStub = stub
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorAvailabilityZonesArgsForCall(i int) (api.AvailabilityZoneInput, bool) {
	fake.updateStagedDirectorAvailabilityZonesMutex.RLock()
	defer fake.updateStagedDirectorAvailabilityZonesMutex.RUnlock()
	argsForCall := fake.updateStagedDirectorAvailabilityZonesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorAvailabilityZonesReturns(result1 error) {
	fake.updateStagedDirectorAvailabilityZonesMutex.Lock()
	defer fake.updateStagedDirectorAvailabilityZonesMutex.Unlock()
	fake.UpdateStagedDirectorAvailabilityZonesStub = nil
	fake.updateStagedDirectorAvailabilityZonesReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorAvailabilityZonesReturnsOnCall(i int, result1 error) {
	fake.updateStagedDirectorAvailabilityZonesMutex.Lock()
	defer fake.updateStagedDirectorAvailabilityZonesMutex.Unlock()
	fake.UpdateStagedDirectorAvailabilityZonesStub = nil
	if fake.updateStagedDirectorAvailabilityZonesReturnsOnCall == nil {
		fake.updateStagedDirectorAvailabilityZonesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateStagedDirectorAvailabilityZonesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorIAASConfigurations(arg1 api.IAASConfigurationsInput) error {
	fake.updateStagedDirectorIAASConfigurationsMutex.Lock()
	ret, specificReturn := fake.updateStagedDirectorIAASConfigurationsReturnsOnCall[len(fake.updateStagedDirectorIAASConfigurationsArgsForCall)]
	fake.updateStagedDirectorIAASConfigurationsArgsForCall = append(fake.updateStagedDirectorIAASConfigurationsArgsForCall, struct {
		arg1 api.IAASConfigurationsInput
	}{arg1})
	fake.recordInvocation("UpdateStagedDirectorIAASConfigurations", []interface{}{arg1})
	fake.updateStagedDirectorIAASConfigurationsMutex.Unlock()
	if fake.UpdateStagedDirectorIAASConfigurationsStub != nil {
		return fake.UpdateStagedDirectorIAASConfigurationsStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.updateStagedDirectorIAASConfigurationsReturns
	return fakeReturns.result1
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorIAASConfigurationsCallCount() int {
	fake.updateStagedDirectorIAASConfigurationsMutex.RLock()
	defer fake.updateStagedDirectorIAASConfigurationsMutex.RUnlock()
	return len(fake.updateStagedDirectorIAASConfigurationsArgsForCall)
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorIAASConfigurationsCalls(stub func(api.IAASConfigurationsInput) error) {
	fake.updateStagedDirectorIAASConfigurationsMutex.Lock()
	defer fake.updateStagedDirectorIAASConfigurationsMutex.Unlock()
	fake.UpdateStagedDirectorIAASConfigurationsStub = stub
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorIAASConfigurationsArgsForCall(i int) api.IAASConfigurationsInput {
	fake.updateStagedDirectorIAASConfigurationsMutex.RLock()
	defer fake.updateStagedDirectorIAASConfigurationsMutex.RUnlock()
	argsForCall := fake.updateStagedDirectorIAASConfigurationsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorIAASConfigurationsReturns(result1 error) {
	fake.updateStagedDirectorIAASConfigurationsMutex.Lock()
	defer fake.updateStagedDirectorIAASConfigurationsMutex.Unlock()
	fake.UpdateStagedDirectorIAASConfigurationsStub = nil
	fake.updateStagedDirectorIAASConfigurationsReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorIAASConfigurationsReturnsOnCall(i int, result1 error) {
	fake.updateStagedDirectorIAASConfigurationsMutex.Lock()
	defer fake.updateStagedDirectorIAASConfigurationsMutex.Unlock()
	fake.UpdateStagedDirectorIAASConfigurationsStub = nil
	if fake.updateStagedDirectorIAASConfigurationsReturnsOnCall == nil {
		fake.updateStagedDirectorIAASConfigurationsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateStagedDirectorIAASConfigurationsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworkAndAZ(arg1 api.NetworkAndAZConfiguration) error {
	fake.updateStagedDirectorNetworkAndAZMutex.Lock()
	ret, specificReturn := fake.updateStagedDirectorNetworkAndAZReturnsOnCall[len(fake.updateStagedDirectorNetworkAndAZArgsForCall)]
	fake.updateStagedDirectorNetworkAndAZArgsForCall = append(fake.updateStagedDirectorNetworkAndAZArgsForCall, struct {
		arg1 api.NetworkAndAZConfiguration
	}{arg1})
	fake.recordInvocation("UpdateStagedDirectorNetworkAndAZ", []interface{}{arg1})
	fake.updateStagedDirectorNetworkAndAZMutex.Unlock()
	if fake.UpdateStagedDirectorNetworkAndAZStub != nil {
		return fake.UpdateStagedDirectorNetworkAndAZStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.updateStagedDirectorNetworkAndAZReturns
	return fakeReturns.result1
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworkAndAZCallCount() int {
	fake.updateStagedDirectorNetworkAndAZMutex.RLock()
	defer fake.updateStagedDirectorNetworkAndAZMutex.RUnlock()
	return len(fake.updateStagedDirectorNetworkAndAZArgsForCall)
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworkAndAZCalls(stub func(api.NetworkAndAZConfiguration) error) {
	fake.updateStagedDirectorNetworkAndAZMutex.Lock()
	defer fake.updateStagedDirectorNetworkAndAZMutex.Unlock()
	fake.UpdateStagedDirectorNetworkAndAZStub = stub
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworkAndAZArgsForCall(i int) api.NetworkAndAZConfiguration {
	fake.updateStagedDirectorNetworkAndAZMutex.RLock()
	defer fake.updateStagedDirectorNetworkAndAZMutex.RUnlock()
	argsForCall := fake.updateStagedDirectorNetworkAndAZArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworkAndAZReturns(result1 error) {
	fake.updateStagedDirectorNetworkAndAZMutex.Lock()
	defer fake.updateStagedDirectorNetworkAndAZMutex.Unlock()
	fake.UpdateStagedDirectorNetworkAndAZStub = nil
	fake.updateStagedDirectorNetworkAndAZReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworkAndAZReturnsOnCall(i int, result1 error) {
	fake.updateStagedDirectorNetworkAndAZMutex.Lock()
	defer fake.updateStagedDirectorNetworkAndAZMutex.Unlock()
	fake.UpdateStagedDirectorNetworkAndAZStub = nil
	if fake.updateStagedDirectorNetworkAndAZReturnsOnCall == nil {
		fake.updateStagedDirectorNetworkAndAZReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateStagedDirectorNetworkAndAZReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworks(arg1 api.NetworkInput) error {
	fake.updateStagedDirectorNetworksMutex.Lock()
	ret, specificReturn := fake.updateStagedDirectorNetworksReturnsOnCall[len(fake.updateStagedDirectorNetworksArgsForCall)]
	fake.updateStagedDirectorNetworksArgsForCall = append(fake.updateStagedDirectorNetworksArgsForCall, struct {
		arg1 api.NetworkInput
	}{arg1})
	fake.recordInvocation("UpdateStagedDirectorNetworks", []interface{}{arg1})
	fake.updateStagedDirectorNetworksMutex.Unlock()
	if fake.UpdateStagedDirectorNetworksStub != nil {
		return fake.UpdateStagedDirectorNetworksStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.updateStagedDirectorNetworksReturns
	return fakeReturns.result1
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworksCallCount() int {
	fake.updateStagedDirectorNetworksMutex.RLock()
	defer fake.updateStagedDirectorNetworksMutex.RUnlock()
	return len(fake.updateStagedDirectorNetworksArgsForCall)
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworksCalls(stub func(api.NetworkInput) error) {
	fake.updateStagedDirectorNetworksMutex.Lock()
	defer fake.updateStagedDirectorNetworksMutex.Unlock()
	fake.UpdateStagedDirectorNetworksStub = stub
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworksArgsForCall(i int) api.NetworkInput {
	fake.updateStagedDirectorNetworksMutex.RLock()
	defer fake.updateStagedDirectorNetworksMutex.RUnlock()
	argsForCall := fake.updateStagedDirectorNetworksArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworksReturns(result1 error) {
	fake.updateStagedDirectorNetworksMutex.Lock()
	defer fake.updateStagedDirectorNetworksMutex.Unlock()
	fake.UpdateStagedDirectorNetworksStub = nil
	fake.updateStagedDirectorNetworksReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorNetworksReturnsOnCall(i int, result1 error) {
	fake.updateStagedDirectorNetworksMutex.Lock()
	defer fake.updateStagedDirectorNetworksMutex.Unlock()
	fake.UpdateStagedDirectorNetworksStub = nil
	if fake.updateStagedDirectorNetworksReturnsOnCall == nil {
		fake.updateStagedDirectorNetworksReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateStagedDirectorNetworksReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorProperties(arg1 api.DirectorProperties) error {
	fake.updateStagedDirectorPropertiesMutex.Lock()
	ret, specificReturn := fake.updateStagedDirectorPropertiesReturnsOnCall[len(fake.updateStagedDirectorPropertiesArgsForCall)]
	fake.updateStagedDirectorPropertiesArgsForCall = append(fake.updateStagedDirectorPropertiesArgsForCall, struct {
		arg1 api.DirectorProperties
	}{arg1})
	fake.recordInvocation("UpdateStagedDirectorProperties", []interface{}{arg1})
	fake.updateStagedDirectorPropertiesMutex.Unlock()
	if fake.UpdateStagedDirectorPropertiesStub != nil {
		return fake.UpdateStagedDirectorPropertiesStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.updateStagedDirectorPropertiesReturns
	return fakeReturns.result1
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorPropertiesCallCount() int {
	fake.updateStagedDirectorPropertiesMutex.RLock()
	defer fake.updateStagedDirectorPropertiesMutex.RUnlock()
	return len(fake.updateStagedDirectorPropertiesArgsForCall)
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorPropertiesCalls(stub func(api.DirectorProperties) error) {
	fake.updateStagedDirectorPropertiesMutex.Lock()
	defer fake.updateStagedDirectorPropertiesMutex.Unlock()
	fake.UpdateStagedDirectorPropertiesStub = stub
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorPropertiesArgsForCall(i int) api.DirectorProperties {
	fake.updateStagedDirectorPropertiesMutex.RLock()
	defer fake.updateStagedDirectorPropertiesMutex.RUnlock()
	argsForCall := fake.updateStagedDirectorPropertiesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorPropertiesReturns(result1 error) {
	fake.updateStagedDirectorPropertiesMutex.Lock()
	defer fake.updateStagedDirectorPropertiesMutex.Unlock()
	fake.UpdateStagedDirectorPropertiesStub = nil
	fake.updateStagedDirectorPropertiesReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) UpdateStagedDirectorPropertiesReturnsOnCall(i int, result1 error) {
	fake.updateStagedDirectorPropertiesMutex.Lock()
	defer fake.updateStagedDirectorPropertiesMutex.Unlock()
	fake.UpdateStagedDirectorPropertiesStub = nil
	if fake.updateStagedDirectorPropertiesReturnsOnCall == nil {
		fake.updateStagedDirectorPropertiesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.updateStagedDirectorPropertiesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConfigureDirectorService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.configureJobResourceConfigMutex.RLock()
	defer fake.configureJobResourceConfigMutex.RUnlock()
	fake.createCustomVMTypesMutex.RLock()
	defer fake.createCustomVMTypesMutex.RUnlock()
	fake.createStagedVMExtensionMutex.RLock()
	defer fake.createStagedVMExtensionMutex.RUnlock()
	fake.deleteCustomVMTypesMutex.RLock()
	defer fake.deleteCustomVMTypesMutex.RUnlock()
	fake.deleteVMExtensionMutex.RLock()
	defer fake.deleteVMExtensionMutex.RUnlock()
	fake.getStagedProductByNameMutex.RLock()
	defer fake.getStagedProductByNameMutex.RUnlock()
	fake.getStagedProductManifestMutex.RLock()
	defer fake.getStagedProductManifestMutex.RUnlock()
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	fake.listInstallationsMutex.RLock()
	defer fake.listInstallationsMutex.RUnlock()
	fake.listStagedVMExtensionsMutex.RLock()
	defer fake.listStagedVMExtensionsMutex.RUnlock()
	fake.listVMTypesMutex.RLock()
	defer fake.listVMTypesMutex.RUnlock()
	fake.updateStagedDirectorAvailabilityZonesMutex.RLock()
	defer fake.updateStagedDirectorAvailabilityZonesMutex.RUnlock()
	fake.updateStagedDirectorIAASConfigurationsMutex.RLock()
	defer fake.updateStagedDirectorIAASConfigurationsMutex.RUnlock()
	fake.updateStagedDirectorNetworkAndAZMutex.RLock()
	defer fake.updateStagedDirectorNetworkAndAZMutex.RUnlock()
	fake.updateStagedDirectorNetworksMutex.RLock()
	defer fake.updateStagedDirectorNetworksMutex.RUnlock()
	fake.updateStagedDirectorPropertiesMutex.RLock()
	defer fake.updateStagedDirectorPropertiesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ConfigureDirectorService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
