// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/pivotal-cf/om/api"
)

type ExpiringCertsService struct {
	ListCertificatesStub        func(string) ([]api.ExpiringCertificate, error)
	listCertificatesMutex       sync.RWMutex
	listCertificatesArgsForCall []struct {
		arg1 string
	}
	listCertificatesReturns struct {
		result1 []api.ExpiringCertificate
		result2 error
	}
	listCertificatesReturnsOnCall map[int]struct {
		result1 []api.ExpiringCertificate
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ExpiringCertsService) ListCertificates(arg1 string) ([]api.ExpiringCertificate, error) {
	fake.listCertificatesMutex.Lock()
	ret, specificReturn := fake.listCertificatesReturnsOnCall[len(fake.listCertificatesArgsForCall)]
	fake.listCertificatesArgsForCall = append(fake.listCertificatesArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ListCertificates", []interface{}{arg1})
	fake.listCertificatesMutex.Unlock()
	if fake.ListCertificatesStub != nil {
		return fake.ListCertificatesStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listCertificatesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ExpiringCertsService) ListCertificatesCallCount() int {
	fake.listCertificatesMutex.RLock()
	defer fake.listCertificatesMutex.RUnlock()
	return len(fake.listCertificatesArgsForCall)
}

func (fake *ExpiringCertsService) ListCertificatesCalls(stub func(string) ([]api.ExpiringCertificate, error)) {
	fake.listCertificatesMutex.Lock()
	defer fake.listCertificatesMutex.Unlock()
	fake.ListCertificatesStub = stub
}

func (fake *ExpiringCertsService) ListCertificatesArgsForCall(i int) string {
	fake.listCertificatesMutex.RLock()
	defer fake.listCertificatesMutex.RUnlock()
	argsForCall := fake.listCertificatesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *ExpiringCertsService) ListCertificatesReturns(result1 []api.ExpiringCertificate, result2 error) {
	fake.listCertificatesMutex.Lock()
	defer fake.listCertificatesMutex.Unlock()
	fake.ListCertificatesStub = nil
	fake.listCertificatesReturns = struct {
		result1 []api.ExpiringCertificate
		result2 error
	}{result1, result2}
}

func (fake *ExpiringCertsService) ListCertificatesReturnsOnCall(i int, result1 []api.ExpiringCertificate, result2 error) {
	fake.listCertificatesMutex.Lock()
	defer fake.listCertificatesMutex.Unlock()
	fake.ListCertificatesStub = nil
	if fake.listCertificatesReturnsOnCall == nil {
		fake.listCertificatesReturnsOnCall = make(map[int]struct {
			result1 []api.ExpiringCertificate
			result2 error
		})
	}
	fake.listCertificatesReturnsOnCall[i] = struct {
		result1 []api.ExpiringCertificate
		result2 error
	}{result1, result2}
}

func (fake *ExpiringCertsService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listCertificatesMutex.RLock()
	defer fake.listCertificatesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ExpiringCertsService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
