// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
)

type ExportInstallationService struct {
	DownloadInstallationAssetCollectionStub        func(outputFile string, pollingInterval int) error
	downloadInstallationAssetCollectionMutex       sync.RWMutex
	downloadInstallationAssetCollectionArgsForCall []struct {
		outputFile      string
		pollingInterval int
	}
	downloadInstallationAssetCollectionReturns struct {
		result1 error
	}
	downloadInstallationAssetCollectionReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ExportInstallationService) DownloadInstallationAssetCollection(outputFile string, pollingInterval int) error {
	fake.downloadInstallationAssetCollectionMutex.Lock()
	ret, specificReturn := fake.downloadInstallationAssetCollectionReturnsOnCall[len(fake.downloadInstallationAssetCollectionArgsForCall)]
	fake.downloadInstallationAssetCollectionArgsForCall = append(fake.downloadInstallationAssetCollectionArgsForCall, struct {
		outputFile      string
		pollingInterval int
	}{outputFile, pollingInterval})
	fake.recordInvocation("DownloadInstallationAssetCollection", []interface{}{outputFile, pollingInterval})
	fake.downloadInstallationAssetCollectionMutex.Unlock()
	if fake.DownloadInstallationAssetCollectionStub != nil {
		return fake.DownloadInstallationAssetCollectionStub(outputFile, pollingInterval)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.downloadInstallationAssetCollectionReturns.result1
}

func (fake *ExportInstallationService) DownloadInstallationAssetCollectionCallCount() int {
	fake.downloadInstallationAssetCollectionMutex.RLock()
	defer fake.downloadInstallationAssetCollectionMutex.RUnlock()
	return len(fake.downloadInstallationAssetCollectionArgsForCall)
}

func (fake *ExportInstallationService) DownloadInstallationAssetCollectionArgsForCall(i int) (string, int) {
	fake.downloadInstallationAssetCollectionMutex.RLock()
	defer fake.downloadInstallationAssetCollectionMutex.RUnlock()
	return fake.downloadInstallationAssetCollectionArgsForCall[i].outputFile, fake.downloadInstallationAssetCollectionArgsForCall[i].pollingInterval
}

func (fake *ExportInstallationService) DownloadInstallationAssetCollectionReturns(result1 error) {
	fake.DownloadInstallationAssetCollectionStub = nil
	fake.downloadInstallationAssetCollectionReturns = struct {
		result1 error
	}{result1}
}

func (fake *ExportInstallationService) DownloadInstallationAssetCollectionReturnsOnCall(i int, result1 error) {
	fake.DownloadInstallationAssetCollectionStub = nil
	if fake.downloadInstallationAssetCollectionReturnsOnCall == nil {
		fake.downloadInstallationAssetCollectionReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.downloadInstallationAssetCollectionReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ExportInstallationService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.downloadInstallationAssetCollectionMutex.RLock()
	defer fake.downloadInstallationAssetCollectionMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ExportInstallationService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
