// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/pivotal-cf/om/api"
)

type GetCertificatesService struct {
	GetDeployedProductCredentialStub        func(api.GetDeployedProductCredentialInput) (api.GetDeployedProductCredentialOutput, error)
	getDeployedProductCredentialMutex       sync.RWMutex
	getDeployedProductCredentialArgsForCall []struct {
		arg1 api.GetDeployedProductCredentialInput
	}
	getDeployedProductCredentialReturns struct {
		result1 api.GetDeployedProductCredentialOutput
		result2 error
	}
	getDeployedProductCredentialReturnsOnCall map[int]struct {
		result1 api.GetDeployedProductCredentialOutput
		result2 error
	}
	ListCertificatesStub        func(string) ([]api.ExpiringCertificate, error)
	listCertificatesMutex       sync.RWMutex
	listCertificatesArgsForCall []struct {
		arg1 string
	}
	listCertificatesReturns struct {
		result1 []api.ExpiringCertificate
		result2 error
	}
	listCertificatesReturnsOnCall map[int]struct {
		result1 []api.ExpiringCertificate
		result2 error
	}
	ListDeployedProductsStub        func() ([]api.DeployedProductOutput, error)
	listDeployedProductsMutex       sync.RWMutex
	listDeployedProductsArgsForCall []struct {
	}
	listDeployedProductsReturns struct {
		result1 []api.DeployedProductOutput
		result2 error
	}
	listDeployedProductsReturnsOnCall map[int]struct {
		result1 []api.DeployedProductOutput
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GetCertificatesService) GetDeployedProductCredential(arg1 api.GetDeployedProductCredentialInput) (api.GetDeployedProductCredentialOutput, error) {
	fake.getDeployedProductCredentialMutex.Lock()
	ret, specificReturn := fake.getDeployedProductCredentialReturnsOnCall[len(fake.getDeployedProductCredentialArgsForCall)]
	fake.getDeployedProductCredentialArgsForCall = append(fake.getDeployedProductCredentialArgsForCall, struct {
		arg1 api.GetDeployedProductCredentialInput
	}{arg1})
	fake.recordInvocation("GetDeployedProductCredential", []interface{}{arg1})
	fake.getDeployedProductCredentialMutex.Unlock()
	if fake.GetDeployedProductCredentialStub != nil {
		return fake.GetDeployedProductCredentialStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getDeployedProductCredentialReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GetCertificatesService) GetDeployedProductCredentialCallCount() int {
	fake.getDeployedProductCredentialMutex.RLock()
	defer fake.getDeployedProductCredentialMutex.RUnlock()
	return len(fake.getDeployedProductCredentialArgsForCall)
}

func (fake *GetCertificatesService) GetDeployedProductCredentialCalls(stub func(api.GetDeployedProductCredentialInput) (api.GetDeployedProductCredentialOutput, error)) {
	fake.getDeployedProductCredentialMutex.Lock()
	defer fake.getDeployedProductCredentialMutex.Unlock()
	fake.GetDeployedProductCredentialStub = stub
}

func (fake *GetCertificatesService) GetDeployedProductCredentialArgsForCall(i int) api.GetDeployedProductCredentialInput {
	fake.getDeployedProductCredentialMutex.RLock()
	defer fake.getDeployedProductCredentialMutex.RUnlock()
	argsForCall := fake.getDeployedProductCredentialArgsForCall[i]
	return argsForCall.arg1
}

func (fake *GetCertificatesService) GetDeployedProductCredentialReturns(result1 api.GetDeployedProductCredentialOutput, result2 error) {
	fake.getDeployedProductCredentialMutex.Lock()
	defer fake.getDeployedProductCredentialMutex.Unlock()
	fake.GetDeployedProductCredentialStub = nil
	fake.getDeployedProductCredentialReturns = struct {
		result1 api.GetDeployedProductCredentialOutput
		result2 error
	}{result1, result2}
}

func (fake *GetCertificatesService) GetDeployedProductCredentialReturnsOnCall(i int, result1 api.GetDeployedProductCredentialOutput, result2 error) {
	fake.getDeployedProductCredentialMutex.Lock()
	defer fake.getDeployedProductCredentialMutex.Unlock()
	fake.GetDeployedProductCredentialStub = nil
	if fake.getDeployedProductCredentialReturnsOnCall == nil {
		fake.getDeployedProductCredentialReturnsOnCall = make(map[int]struct {
			result1 api.GetDeployedProductCredentialOutput
			result2 error
		})
	}
	fake.getDeployedProductCredentialReturnsOnCall[i] = struct {
		result1 api.GetDeployedProductCredentialOutput
		result2 error
	}{result1, result2}
}

func (fake *GetCertificatesService) ListCertificates(arg1 string) ([]api.ExpiringCertificate, error) {
	fake.listCertificatesMutex.Lock()
	ret, specificReturn := fake.listCertificatesReturnsOnCall[len(fake.listCertificatesArgsForCall)]
	fake.listCertificatesArgsForCall = append(fake.listCertificatesArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("ListCertificates", []interface{}{arg1})
	fake.listCertificatesMutex.Unlock()
	if fake.ListCertificatesStub != nil {
		return fake.ListCertificatesStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listCertificatesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GetCertificatesService) ListCertificatesCallCount() int {
	fake.listCertificatesMutex.RLock()
	defer fake.listCertificatesMutex.RUnlock()
	return len(fake.listCertificatesArgsForCall)
}

func (fake *GetCertificatesService) ListCertificatesCalls(stub func(string) ([]api.ExpiringCertificate, error)) {
	fake.listCertificatesMutex.Lock()
	defer fake.listCertificatesMutex.Unlock()
	fake.ListCertificatesStub = stub
}

func (fake *GetCertificatesService) ListCertificatesArgsForCall(i int) string {
	fake.listCertificatesMutex.RLock()
	defer fake.listCertificatesMutex.RUnlock()
	argsForCall := fake.listCertificatesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *GetCertificatesService) ListCertificatesReturns(result1 []api.ExpiringCertificate, result2 error) {
	fake.listCertificatesMutex.Lock()
	defer fake.listCertificatesMutex.Unlock()
	fake.ListCertificatesStub = nil
	fake.listCertificatesReturns = struct {
		result1 []api.ExpiringCertificate
		result2 error
	}{result1, result2}
}

func (fake *GetCertificatesService) ListCertificatesReturnsOnCall(i int, result1 []api.ExpiringCertificate, result2 error) {
	fake.listCertificatesMutex.Lock()
	defer fake.listCertificatesMutex.Unlock()
	fake.ListCertificatesStub = nil
	if fake.listCertificatesReturnsOnCall == nil {
		fake.listCertificatesReturnsOnCall = make(map[int]struct {
			result1 []api.ExpiringCertificate
			result2 error
		})
	}
	fake.listCertificatesReturnsOnCall[i] = struct {
		result1 []api.ExpiringCertificate
		result2 error
	}{result1, result2}
}

func (fake *GetCertificatesService) ListDeployedProducts() ([]api.DeployedProductOutput, error) {
	fake.listDeployedProductsMutex.Lock()
	ret, specificReturn := fake.listDeployedProductsReturnsOnCall[len(fake.listDeployedProductsArgsForCall)]
	fake.listDeployedProductsArgsForCall = append(fake.listDeployedProductsArgsForCall, struct {
	}{})
	fake.recordInvocation("ListDeployedProducts", []interface{}{})
	fake.listDeployedProductsMutex.Unlock()
	if fake.ListDeployedProductsStub != nil {
		return fake.ListDeployedProductsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listDeployedProductsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GetCertificatesService) ListDeployedProductsCallCount() int {
	fake.listDeployedProductsMutex.RLock()
	defer fake.listDeployedProductsMutex.RUnlock()
	return len(fake.listDeployedProductsArgsForCall)
}

func (fake *GetCertificatesService) ListDeployedProductsCalls(stub func() ([]api.DeployedProductOutput, error)) {
	fake.listDeployedProductsMutex.Lock()
	defer fake.listDeployedProductsMutex.Unlock()
	fake.ListDeployedProductsStub = stub
}

func (fake *GetCertificatesService) ListDeployedProductsReturns(result1 []api.DeployedProductOutput, result2 error) {
	fake.listDeployedProductsMutex.Lock()
	defer fake.listDeployedProductsMutex.Unlock()
	fake.ListDeployedProductsStub = nil
	fake.listDeployedProductsReturns = struct {
		result1 []api.DeployedProductOutput
		result2 error
	}{result1, result2}
}

func (fake *GetCertificatesService) ListDeployedProductsReturnsOnCall(i int, result1 []api.DeployedProductOutput, result2 error) {
	fake.listDeployedProductsMutex.Lock()
	defer fake.listDeployedProductsMutex.Unlock()
	fake.ListDeployedProductsStub = nil
	if fake.listDeployedProductsReturnsOnCall == nil {
		fake.listDeployedProductsReturnsOnCall = make(map[int]struct {
			result1 []api.DeployedProductOutput
			result2 error
		})
	}
	fake.listDeployedProductsReturnsOnCall[i] = struct {
		result1 []api.DeployedProductOutput
		result2 error
	}{result1, result2}
}

func (fake *GetCertificatesService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getDeployedProductCredentialMutex.RLock()
	defer fake.getDeployedProductCredentialMutex.RUnlock()
	fake.listCertificatesMutex.RLock()
	defer fake.listCertificatesMutex.RUnlock()
	fake.listDeployedProductsMutex.RLock()
	defer fake.listDeployedProductsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GetCertificatesService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
