// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/pivotal-cf/om/api"
)

type KubernetesDistributionsService struct {
	InfoStub        func() (api.Info, error)
	infoMutex       sync.RWMutex
	infoArgsForCall []struct {
	}
	infoReturns struct {
		result1 api.Info
		result2 error
	}
	infoReturnsOnCall map[int]struct {
		result1 api.Info
		result2 error
	}
	ListKubernetesDistributionsStub        func() (api.KubernetesDistributionAssociationsResponse, error)
	listKubernetesDistributionsMutex       sync.RWMutex
	listKubernetesDistributionsArgsForCall []struct {
	}
	listKubernetesDistributionsReturns struct {
		result1 api.KubernetesDistributionAssociationsResponse
		result2 error
	}
	listKubernetesDistributionsReturnsOnCall map[int]struct {
		result1 api.KubernetesDistributionAssociationsResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *KubernetesDistributionsService) Info() (api.Info, error) {
	fake.infoMutex.Lock()
	ret, specificReturn := fake.infoReturnsOnCall[len(fake.infoArgsForCall)]
	fake.infoArgsForCall = append(fake.infoArgsForCall, struct {
	}{})
	fake.recordInvocation("Info", []interface{}{})
	fake.infoMutex.Unlock()
	if fake.InfoStub != nil {
		return fake.InfoStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.infoReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *KubernetesDistributionsService) InfoCallCount() int {
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	return len(fake.infoArgsForCall)
}

func (fake *KubernetesDistributionsService) InfoCalls(stub func() (api.Info, error)) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = stub
}

func (fake *KubernetesDistributionsService) InfoReturns(result1 api.Info, result2 error) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = nil
	fake.infoReturns = struct {
		result1 api.Info
		result2 error
	}{result1, result2}
}

func (fake *KubernetesDistributionsService) InfoReturnsOnCall(i int, result1 api.Info, result2 error) {
	fake.infoMutex.Lock()
	defer fake.infoMutex.Unlock()
	fake.InfoStub = nil
	if fake.infoReturnsOnCall == nil {
		fake.infoReturnsOnCall = make(map[int]struct {
			result1 api.Info
			result2 error
		})
	}
	fake.infoReturnsOnCall[i] = struct {
		result1 api.Info
		result2 error
	}{result1, result2}
}

func (fake *KubernetesDistributionsService) ListKubernetesDistributions() (api.KubernetesDistributionAssociationsResponse, error) {
	fake.listKubernetesDistributionsMutex.Lock()
	ret, specificReturn := fake.listKubernetesDistributionsReturnsOnCall[len(fake.listKubernetesDistributionsArgsForCall)]
	fake.listKubernetesDistributionsArgsForCall = append(fake.listKubernetesDistributionsArgsForCall, struct {
	}{})
	fake.recordInvocation("ListKubernetesDistributions", []interface{}{})
	fake.listKubernetesDistributionsMutex.Unlock()
	if fake.ListKubernetesDistributionsStub != nil {
		return fake.ListKubernetesDistributionsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listKubernetesDistributionsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *KubernetesDistributionsService) ListKubernetesDistributionsCallCount() int {
	fake.listKubernetesDistributionsMutex.RLock()
	defer fake.listKubernetesDistributionsMutex.RUnlock()
	return len(fake.listKubernetesDistributionsArgsForCall)
}

func (fake *KubernetesDistributionsService) ListKubernetesDistributionsCalls(stub func() (api.KubernetesDistributionAssociationsResponse, error)) {
	fake.listKubernetesDistributionsMutex.Lock()
	defer fake.listKubernetesDistributionsMutex.Unlock()
	fake.ListKubernetesDistributionsStub = stub
}

func (fake *KubernetesDistributionsService) ListKubernetesDistributionsReturns(result1 api.KubernetesDistributionAssociationsResponse, result2 error) {
	fake.listKubernetesDistributionsMutex.Lock()
	defer fake.listKubernetesDistributionsMutex.Unlock()
	fake.ListKubernetesDistributionsStub = nil
	fake.listKubernetesDistributionsReturns = struct {
		result1 api.KubernetesDistributionAssociationsResponse
		result2 error
	}{result1, result2}
}

func (fake *KubernetesDistributionsService) ListKubernetesDistributionsReturnsOnCall(i int, result1 api.KubernetesDistributionAssociationsResponse, result2 error) {
	fake.listKubernetesDistributionsMutex.Lock()
	defer fake.listKubernetesDistributionsMutex.Unlock()
	fake.ListKubernetesDistributionsStub = nil
	if fake.listKubernetesDistributionsReturnsOnCall == nil {
		fake.listKubernetesDistributionsReturnsOnCall = make(map[int]struct {
			result1 api.KubernetesDistributionAssociationsResponse
			result2 error
		})
	}
	fake.listKubernetesDistributionsReturnsOnCall[i] = struct {
		result1 api.KubernetesDistributionAssociationsResponse
		result2 error
	}{result1, result2}
}

func (fake *KubernetesDistributionsService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.infoMutex.RLock()
	defer fake.infoMutex.RUnlock()
	fake.listKubernetesDistributionsMutex.RLock()
	defer fake.listKubernetesDistributionsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *KubernetesDistributionsService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
