// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/pivotal-cf/om/api"
)

type StemcellService struct {
	UploadStub        func(api.StemcellUploadInput) (api.StemcellUploadOutput, error)
	uploadMutex       sync.RWMutex
	uploadArgsForCall []struct {
		arg1 api.StemcellUploadInput
	}
	uploadReturns struct {
		result1 api.StemcellUploadOutput
		result2 error
	}
}

func (fake *StemcellService) Upload(arg1 api.StemcellUploadInput) (api.StemcellUploadOutput, error) {
	fake.uploadMutex.Lock()
	fake.uploadArgsForCall = append(fake.uploadArgsForCall, struct {
		arg1 api.StemcellUploadInput
	}{arg1})
	fake.uploadMutex.Unlock()
	if fake.UploadStub != nil {
		return fake.UploadStub(arg1)
	} else {
		return fake.uploadReturns.result1, fake.uploadReturns.result2
	}
}

func (fake *StemcellService) UploadCallCount() int {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return len(fake.uploadArgsForCall)
}

func (fake *StemcellService) UploadArgsForCall(i int) api.StemcellUploadInput {
	fake.uploadMutex.RLock()
	defer fake.uploadMutex.RUnlock()
	return fake.uploadArgsForCall[i].arg1
}

func (fake *StemcellService) UploadReturns(result1 api.StemcellUploadOutput, result2 error) {
	fake.UploadStub = nil
	fake.uploadReturns = struct {
		result1 api.StemcellUploadOutput
		result2 error
	}{result1, result2}
}
